import { writeFileSync } from "fs";
import { startGenerate } from "./jit.js";
import { cssFolder, packagePath } from "../builder/controller.js";

writeFileSync(
  `${packagePath}/jit/JitGenerated.js`,
  `/* This file is generated by Moon Style. Do not edit it manually. */
    export const JitGenerated={}`
);
writeFileSync(`${cssFolder}/moon/moon.jit.css`, `/* This file is generated by Moon Style. Do not edit it manually. */`);
startGenerate();
