// vite-plugin-moon.js
import { Watcher, PurgeCSS } from "./workflow.js";
import { buildIcons, resolveConfig } from "./vite-plugin-icons.js";
import fs from "fs";
import path from "path";

const INIT_CONTENT = `import Moon from "moon-style";\nimport "./main.css";\nMoon.init();\n`;

// ── Virtual module: virtual:moon-icons/sprite-url ─────────────────────────────
// Provides a cache-busted sprite URL to the DS layer without any generated file
// visible in the user's workspace. Invalidated on every HMR sprite rebuild.

const VIRTUAL_ID = "virtual:moon-icons/sprite-url";
const RESOLVED_ID = "\0" + VIRTUAL_ID; // Vite convention: prefix with \0

let spriteVersion = Date.now();

function buildSpriteModule() {
  return `export const spriteUrl = "/icons/sprite.svg?v=${spriteVersion}";`;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function ensureGitignore() {
  const gitignorePath = "./.gitignore";
  const entries = ["moon/"];

  let content = "";
  try {
    content = fs.readFileSync(gitignorePath, "utf8");
  } catch {}

  const missing = entries.filter((e) => !content.includes(e));
  if (missing.length) {
    const block = `\n# Generated by moon-style (do not commit)\n${missing.join("\n")}\n`;
    fs.appendFileSync(gitignorePath, block, "utf8");
  }
}

function ensureInitFile() {
  const dir = "./moon";
  const initPath = `${dir}/init.ts`;
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  if (!fs.existsSync(initPath)) {
    fs.writeFileSync(initPath, INIT_CONTENT, "utf8");
  }
}

// ── Plugin ────────────────────────────────────────────────────────────────────

export default function moonPlugin() {
  const iconsConfig = resolveConfig();
  const watchedDir = path.resolve(iconsConfig.svgDir);

  return {
    name: "vite-plugin-moon",

    // ── Virtual module resolution ────────────────────────────────────────────
    resolveId(id: string) {
      if (id === VIRTUAL_ID) return RESOLVED_ID;
      return undefined;
    },

    load(id: string) {
      if (id === RESOLVED_ID) return buildSpriteModule();
      return undefined;
    },

    // ── Build ────────────────────────────────────────────────────────────────
    async buildStart() {
      if (process.env.NODE_ENV === "production") await PurgeCSS();
      ensureGitignore();
      ensureInitFile();
      await buildIcons(iconsConfig);
    },

    configureServer(server: any) {
      ensureInitFile();
      if (!process.env.NODE_ENV || process.env.NODE_ENV === "development") Watcher();

      const { watcher, ws, moduleGraph } = server;
      if (fs.existsSync(watchedDir)) {
        watcher.add(`${watchedDir}/**/*.svg`);
      }

      let buildTimeout: NodeJS.Timeout | null = null;
      let pendingFiles = new Set<string>();

      async function debouncedRebuild() {
        if (pendingFiles.size === 0) return;
        const count = pendingFiles.size;
        console.log(`[moon-icons] Processing ${count} changed file(s)...`);
        pendingFiles.clear();

        try {
          await buildIcons(iconsConfig);

          // Bump version so the virtual module re-resolves with a fresh cache-buster
          spriteVersion = Date.now();

          // Invalidate the virtual module so Vite re-evaluates it
          const virtualMod = moduleGraph.getModuleById(RESOLVED_ID);
          if (virtualMod) moduleGraph.invalidateModule(virtualMod);

          // Invalidate the names module for TypeScript auto-completion
          const namesMod = moduleGraph.getModuleById(path.resolve(iconsConfig.namesOut));
          if (namesMod) moduleGraph.invalidateModule(namesMod);

          ws.send({ type: "full-reload" });
        } catch (err) {
          console.error("[moon-icons] Build error:", err);
        }
      }

      function rebuild(file: string) {
        if (!file.startsWith(watchedDir) || !file.endsWith(".svg")) return;
        pendingFiles.add(file);

        if (buildTimeout) clearTimeout(buildTimeout);
        buildTimeout = setTimeout(debouncedRebuild, 300); // 300ms debounce
      }

      watcher.on("change", rebuild);
      watcher.on("add", rebuild);
      watcher.on("unlink", rebuild);
    },

    transformIndexHtml: {
      order: "pre" as const,
      handler(html: string) {
        const tag = `<script type="module" src="/moon/init.ts"></script>`;
        return html.replace("</head>", `    ${tag}\n  </head>`);
      },
    },

    async closeBundle() {},
  };
}
