import { Controller } from "./controller.js";
import { hexToRGB } from "./utils.js";

const DEFAULT_COLOR_PROPS = ["bg", "text", "fill", "border"];

export const getColors = async () => {
  const colors = Controller.config.colors as ConfigColors;
  const { staticColors } = colors;
  const themes: ConfigColors["themes"] = JSON.parse(JSON.stringify(colors.themes));

  Controller.ColorsVariables = getAllColorsNamesVaribles(themes, staticColors);

  const root = Object.entries(staticColors).reduce((acc, [key, value]) => {
    const rgbKey = `rgb-${key}`;
    acc[rgbKey] = hexToRGB(value);
    acc[key] = `rgb(var(--${rgbKey}))`;
    return acc;
  }, {} as any);

  Object.keys(themes).forEach((key) => {
    const _Theme = themes[key];
    const rgbTheme: Record<string, string> = {};
    Object.entries(_Theme).forEach(([cK, hex]) => {
      rgbTheme[`rgb-${cK}`] = hexToRGB(hex);
      root[`${cK}`] = `rgb(var(--rgb-${cK}))`;
    });
    themes[key] = rgbTheme;
  });

  const { options, defaultProps } = handleOptions(colors.options);

  Object.entries(options).forEach(([colorName, { opacities }]) => {
    if (!opacities) return;
    appendTheGeneratedOpacitiesToTheStaticColors(opacities, colorName, root, options);
  });

  const themesContent = Object.entries({ root: root, ...themes })
    .map(
      ([themeKey, themeValues]) =>
        `${themeKey === "root" ? ":" : "."}${themeKey}{${Object.entries(themeValues)
          .map(([key, value]) => `--${key}:${value};`)
          .join("")}}`,
    )
    .join("\n");

  let colorsContent = "/*classes*/\n";

  Object.keys(root).forEach((key) => {
    const _colorsProps = options[key]?.props ?? defaultProps;
    if (key.startsWith("rgb-")) return;
    _colorsProps?.forEach((propKey) => {
      const _class = `${propKey}-${key}`;
      const variable = `--${key}`;
      const cssProp = colorsKeys[propKey as keyof typeof colorsKeys];
      if (!cssProp) return;
      const classValue = `${cssProp}:var(${variable})`;
      colorsContent += `.${_class}{${classValue};} `;
      Controller.GeneratedClasses[_class] = classValue;
    });
    colorsContent += `\n`;
  });

  return `/* This file is generated by Moon Style. Do not edit it manually. */
${themesContent}\n\n${colorsContent}`;
};

const colorsKeys = {
  bg: "background-color",
  text: "color",
  fill: "fill",
  border: "border-color",
  stroke: "stroke",
};

const getAllColorsNamesVaribles = (themes: { [key: string]: { [key: string]: string } }, staticColors: { [key: string]: string }) =>
  [
    ...Object.values(themes)
      .map((v) => Object.keys(v))
      .flat(),
    ...Object.keys(staticColors),
  ].filter((v, i, a) => a.indexOf(v) === i);

function appendTheGeneratedOpacitiesToTheStaticColors(
  opacities: any,
  key: string,
  staticColors: { [key: string]: string },
  options: { [key: string]: { props?: string[] | undefined; opacities?: number[] | undefined } },
) {
  opacities.forEach((value: any) => {
    const colorWithOpacity = `${key}-${value * 1000}`;
    staticColors[colorWithOpacity] = `rgba(var(--rgb-${key}),${value})`;
    if (options[colorWithOpacity] || !options[key]) return;
    options[colorWithOpacity] = { props: options[key]?.props };
  });
}

type HandleOptionsResult = {
  options: { [key: string]: { props?: string[]; opacities?: number[] } };
  defaultProps: string[];
};

function handleOptions(sourceOptions: { [key: string]: { props?: string[]; opacities?: number[] } }): HandleOptionsResult {
  if (!sourceOptions) return { options: {}, defaultProps: DEFAULT_COLOR_PROPS };

  const options = { ...sourceOptions };

  if (!options["*"]) return { options, defaultProps: DEFAULT_COLOR_PROPS };

  const { opacities, props } = options["*"];
  const defaultProps = props ?? DEFAULT_COLOR_PROPS;

  Controller.ColorsVariables.forEach((key) => {
    if (!options[key]) options[key] = { opacities };
    else if (!options[key].opacities) options[key] = { ...options[key], opacities };
  });

  const { "*": _, ...rest } = options;
  return { options: rest, defaultProps };
}

type ConfigColors = {
  options: {
    [key: string]: {
      props?: string[];
      opacities?: number[];
    };
  };
  staticColors: {
    [key: string]: string;
  };
  themes: {
    [key: string]: {
      [key: string]: string;
    };
  };
};
