import { getColors } from "./buildColors.js";
import { getStaticCss } from "./buildStaticClasses.js";
import { getStyles } from "./buildStyles.js";
import { createFile, createFolder, fileExists } from "../helpers/owlFs.js";
import { fileURLToPath } from "url";
import path from "path";

// Resolve to the directory containing this compiled file (dist/builder/).
// This works whether the CLI is run via `yarn moon`, `npx`, or `node /abs/path/moon.js`.
const _dir = path.dirname(fileURLToPath(import.meta.url));
export const packagePath = path.resolve(_dir, ".."); // dist/
export const cssFolder = ".";

const DEFAULT_PROPS_BY_SHORT_NAMES = {
  bg: "background-color",
  text: "color",
  round: "border-radius",
  content: (v: string) => `content:attr(data-${v})`,
} as { [key: string]: any };

function deepMerge(target: any, source: any): any {
  const result = { ...target };
  for (const key of Object.keys(source)) {
    if (
      source[key] &&
      typeof source[key] === "object" &&
      !Array.isArray(source[key]) &&
      target[key] &&
      typeof target[key] === "object" &&
      !Array.isArray(target[key])
    ) {
      result[key] = deepMerge(target[key], source[key]);
    } else {
      result[key] = source[key];
    }
  }
  return result;
}

export const Controller = {
  createStyles: async () => {
    Controller.reset();
    Controller.PropsByShortNames.m = (v: string) => `margin:${v}`;
    await createFolder(`${cssFolder}/moon`, {
      main: { name: "main.css", content: await getMainCss() },
      moon: { name: "moon.styles.css", content: await getStyles() },
      themes: { name: "moon.themes.css", content: await getColors() },
      static: { name: "moon.static.css", content: await getStaticCss() },
    });

    if (!(await fileExists(`${cssFolder}/moon/moon.jit.css`)))
      await createFile({ dir: `${cssFolder}/moon`, name: "moon.jit.css", content: "/* This file is generated by Moon Style. Do not edit it manually. */" });

    await createFile({ dir: "./", name: "Moon.Types.ts", content: await getMoonTypes() });
  },

  reset: () => {
    Controller.GeneratedClasses = {};
    Controller.StylesVariables = [];
    Controller.ColorsVariables = [];
    Controller.PropsByShortNames = { ...DEFAULT_PROPS_BY_SHORT_NAMES };
  },

  init: async (config: any) => {
    Controller.config = deepMerge(Controller.config, config);
  },

  GeneratedClasses: {} as { [key: string]: string },

  StylesVariables: [] as string[],
  ColorsVariables: [] as string[],
  JitGenerated: {} as { [key: string]: string },
  PropsByShortNames: {
    bg: "background-color",
    text: "color",
    round: "border-radius",
    content: (v: string) => `content:attr(data-${v})`,
  } as { [key: string]: any },
  config: {
    useJit: true,
    useStaticNumbers: false,
    projectDir: "./src",
    content: ["./src/**/*.{html,js,jsx,tsx}"],
    colors: {
      options: {},
      staticColors: {},
      themes: {
        light: {},
        dark: {},
      },
    },
    styles: [
      {
        props: { padding: "p", margin: "m", gap: "gap", inset: "inset", top: "top", left: "left", right: "right", bottom: "bottom" },
        variableName: "spacing",
        values: {
          "0": "0",
          xs: "2px",
          sm: "4px",
          md: "8px",
          lg: "10px",
          xl: "12px",
          "2x": "16px",
          "3x": "20px",
          "4x": "26px",
          "5x": "32px",
          "6x": "40px",
        },
      },
    ],
  },
};

const getMoonTypes = async () => {
  const colorsArray = Controller.ColorsVariables.map((v) => `"${v}"`).join(", ");
  const themes = Controller.config.colors.themes;
  const themesArray = Object.keys(themes)
    .map((theme) => `"${theme}"`)
    .join(", ");
  return `// This file is generated by Moon Style. Do not edit it manually.
export const themes = [${themesArray}] as const;
export type Theme = (typeof themes)[number];
export const colors = [${colorsArray}] as const;
export type Color = (typeof colors)[number];
`;
};

const getMainCss = async () => `/* This file is generated by Moon Style. Do not edit it manually. */
  @import url('./moon.styles.css');
  @import url('./moon.themes.css');
  @import url('./moon.static.css');
  @import url('./moon.jit.css');
  `;
